export default `<?xml version="1.0" encoding="UTF-8"?>
<creditBureau xmlns="http://www.transunion.com/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.transunion.com/namespace">
	<document>response</document>
	<version>2.33</version>
	<transactionControl>
		<subscriber>
			<industryCode>F</industryCode>
			<memberCode>8207115</memberCode>
			<inquirySubscriberPrefixCode>0622</inquirySubscriberPrefixCode>
		</subscriber>
		<options>
			<country>us</country>
			<language>en</language>
			<productVersion>standard</productVersion>
		</options>
		<tracking>
			<transactionTimeStamp>2022-01-27T17:53:12.838-06:00</transactionTimeStamp>
		</tracking>
	</transactionControl>
	<product>
		<code>08000</code>
		<subject>
			<number>1</number>
			<subjectRecord>
				<fileNumber>01</fileNumber>
				<fileSummary>
					<fileHitIndicator>regularHit</fileHitIndicator>
					<ssnMatchIndicator>fileOnly</ssnMatchIndicator>
					<consumerStatementIndicator>true</consumerStatementIndicator>
					<market>11</market>
					<submarket>DT</submarket>
					<creditDataStatus>
						<suppressed>false</suppressed>
						<doNotPromote>
							<indicator>false</indicator>
						</doNotPromote>
						<freeze>
							<indicator>false</indicator>
						</freeze>
						<minor>false</minor>
						<disputed>false</disputed>
					</creditDataStatus>
					<inFileSinceDate estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false">1993-04-01</inFileSinceDate>
				</fileSummary>
				<indicative>
					<name source="file">
						<person>
							<first>ROBERT</first>
							<middle>E</middle>
							<last>UPHOLD</last>
							<generationalSuffix>SR</generationalSuffix>
						</person>
					</name>
					<address source="file">
						<status>current</status>
						<qualifier>personal</qualifier>
						<street>
							<number>27366</number>
							<name>PERRY</name>
							<type>ST</type>
						</street>
						<location>
							<city>ROSEVILLE</city>
							<state>MI</state>
							<zipCode>48066</zipCode>
						</location>
						<dateReported estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false">2016-01-19</dateReported>
					</address>
					<address source="file">
						<status>previous</status>
						<qualifier>personal</qualifier>
						<street>
							<number>2251</number>
							<name>FORT APACHE</name>
							<preDirectional>S</preDirectional>
							<type>RD</type>
						</street>
						<location>
							<city>LAS VEGAS</city>
							<state>NV</state>
							<zipCode>89117</zipCode>
						</location>
						<dateReported estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false">2017-08-31</dateReported>
					</address>
					<address source="file">
						<status>previous</status>
						<qualifier>personal</qualifier>
						<street>
							<number>8530</number>
							<name>SAHARA</name>
							<preDirectional>W</preDirectional>
							<type>AV</type>
							<unit>
								<number>214</number>
							</unit>
						</street>
						<location>
							<city>LAS VEGAS</city>
							<state>NV</state>
							<zipCode>89117</zipCode>
						</location>
					</address>
					<socialSecurity source="file">
						<number>666484418</number>
					</socialSecurity>
					<dateOfBirth estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false" source="file">1956-08-01</dateOfBirth>
					<employment source="file">
						<employer>
							<unparsed>EMPLOYER X</unparsed>
						</employer>
						<occupation>RETIRED</occupation>
						<dateOnFileSince estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false">2020-03-06</dateOnFileSince>
						<dateEffective estimatedDay="false" estimatedMonth="false" estimatedCentury="false" estimatedYear="false">2017-04-08</dateEffective>
					</employment>
				</indicative>
				<consumerFileData>
					<consumerStatement>
						<type>regular</type>
						<text>DO NOT CONFUSE WITH CONSUMERS OF SIMILAR IDENTIFICATION; VERIFY ALL IDENTIFYING INFORMATION.</text>
					</consumerStatement>
				</consumerFileData>
				<custom>
					<credit>
						<creditSummary>
							<revolvingAmount>
								<percentAvailableCredit>089</percentAvailableCredit>
								<highCredit>000033937</highCredit>
								<creditLimit>000062200</creditLimit>
								<currentBalance>000006840</currentBalance>
								<pastDue>000000000</pastDue>
								<monthlyPayment>000000155</monthlyPayment>
							</revolvingAmount>
							<installmentAmount>
								<highCredit>000080265</highCredit>
								<creditLimit>000000000</creditLimit>
								<currentBalance>000039195</currentBalance>
								<pastDue>000000189</pastDue>
								<monthlyPayment>000000907</monthlyPayment>
							</installmentAmount>
							<mortgageAmount>
								<highCredit>000093000</highCredit>
								<creditLimit>000000000</creditLimit>
								<currentBalance>000076387</currentBalance>
								<pastDue>000000000</pastDue>
								<monthlyPayment>000000557</monthlyPayment>
							</mortgageAmount>
							<totalAmount>
								<highCredit>000207202</highCredit>
								<creditLimit>000062200</creditLimit>
								<currentBalance>000122422</currentBalance>
								<pastDue>000000189</pastDue>
								<monthlyPayment>000001619</monthlyPayment>
							</totalAmount>
							<recordCounts reportingPeriod="totalHistory">
								<publicRecordCount>000</publicRecordCount>
								<collectionCount>000</collectionCount>
								<totalTradeCount>032</totalTradeCount>
								<negativeTradeCount>001</negativeTradeCount>
								<historicalNegativeTradeCount>001</historicalNegativeTradeCount>
								<historicalNegativeOccurrencesCount>001</historicalNegativeOccurrencesCount>
								<revolvingTradeCount>014</revolvingTradeCount>
								<installmentTradeCount>014</installmentTradeCount>
								<mortgageTradeCount>004</mortgageTradeCount>
								<openTradeCount>000</openTradeCount>
								<unspecifiedTradeCount>000</unspecifiedTradeCount>
								<totalInquiryCount>004</totalInquiryCount>
							</recordCounts>
						</creditSummary>
					</credit>
					<modelReport>
						<complianceCondition>
							<type>trade</type>
							<sourceName>
								<unparsed>TARGET N.B.</unparsed>
							</sourceName>
							<accountNumber>6X9X6</accountNumber>
							<remark>
								<code>CBC</code>
							</remark>
						</complianceCondition>
					</modelReport>
				</custom>
				<addOnProduct>
					<code>00V60</code>
					<status>defaultDelivered</status>
					<scoreModel>
						<score>
							<results>+667</results>
							<derogatoryAlert>false</derogatoryAlert>
							<fileInquiriesImpactedScore>false</fileInquiriesImpactedScore>
							<factors>
								<factor>
									<rank>1</rank>
									<code>09</code>
								</factor>
								<factor>
									<rank>2</rank>
									<code>07</code>
								</factor>
								<factor>
									<rank>3</rank>
									<code>85</code>
								</factor>
								<factor>
									<rank>4</rank>
									<code>05</code>
								</factor>
							</factors>
							<scoreCard>12</scoreCard>
						</score>
					</scoreModel>
				</addOnProduct>
				<addOnProduct>
					<code>00WR3</code>
					<status>defaultDelivered</status>
					<scoreModel>
						<characteristic>
                            <algorithmID>00WR3</algorithmID>
                            <id>AU01S</id>
                            <value>0000000002</value>
                        </characteristic>
						<characteristic>
							<algorithmID>00WR3</algorithmID>
							<id>BC33S</id>
							<value>000004321</value>
						</characteristic>
						<characteristic>
							<algorithmID>00WR3</algorithmID>
							<id>US33S</id>
							<value>000001234</value>
						</characteristic>
					</scoreModel>
				</addOnProduct>
			</subjectRecord>
		</subject>
	</product>
</creditBureau>`
